services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm test -- --watchAll=false
    environment:
      CI: "true"
    volumes:
      - .:/app
      - /app/node_modules
    